local:
  # список интерфейсов
  interfaces:
    internal: 'enp0s3'
    external: 'enp0s8'
    fb: 'ifb0'
  # список наших IP для пропуска
  ip:
    - '10.10.0.1'
    - '185.10.83.2'
    - '185.10.80.1'

staticarp:
  filename: '/etc/ether'

# сервер авторизации (цель для DNAT)
auth:
  ip: '185.10.83.6'

# список ipset листов
ipset:
  whitelist: 'whitelist'
  authlist: 'authmaclist'
  keepttl: 'keepttl'

# список цепочек iptables
iptables:
  chains:
    # цепочка белого списка
    white: 'WHITE'
    # цепочка проверки авторизации и маркирования неавторизованных
    auth: 'AUTHMARK'
    # цепочка управления ttl
    ttl: 'CHANGETTL'
    # цепочка
    drop: 'DROPMARKED'

# ratelimiter
ratelimit:
  in: 'tin'
  out: 'tout'

# настройки протоколов rpc
rpc:
  zeromq:
    enabled: True
    ports:
      push_pull: 'tcp://*:5558'
      req_resp: 'tcp://*:5559'
  rabbitmq:
    enabled: True
    host: '192.168.99.100'
    port: 32769
    username: 'guest'
    password: 'guest'
    vhost: 'dev'
    exchange: 'general'
    key: '#.*.igrec'
    region: '.#'  # или '.dev', '.cb'
  grpc:
    enabled: False
