[local]
ip = [ "10.10.0.1", "185.10.83.2", "185.10.80.1" ]

  [local.interfaces]
  internal = "enp0s3"
  external = "enp0s8"

[staticarp]
filename = "/etc/ether"

[auth]
ip = "185.10.83.6"

[ipset]
whitelist = "whitelist"
authlist = "authmaclist"
keepttl = "keepttl"

[iptables.chains]
white = "WHITE"
auth = "AUTHMARK"
ttl = "CHANGETTL"
drop = "DROPMARKED"

[rpc.zeromq]
enabled = true

  [rpc.zeromq.ports]
  push_pull = "tcp://*:5558"
  req_resp = "tcp://*:5559"
