local:
  # список интерфейсов
  interfaces:
    internal: 'enp4s0'
    external: 'enp1s0'

  # список наших IP для пропуска
  ip:
    - '10.10.0.1'
    - '185.10.83.2'
    - '185.10.80.1'

staticarp:
  filename: '/etc/ether'

# сервер авторизации (цель для DNAT)
auth:
  ip: '185.10.83.6'

# список ipset листов
ipset:
  whitelist: 'whitelist'
  authlist: 'authmaclist'

# список цепочек iptables
iptables:
  chains:
    # цепочка белого списка
    white: 'WHITE'
    # цепочка проверки авторизации и маркирования неавторизованных
    auth: 'AUTHMARK'
    # цепочка
    drop: 'DROPMARKED'

# настройки протоколов rpc
rpc:
  zeromq:
    enabled: True
    ports:
      push_pull: 'tcp://*:5558'
      req_resp: 'tcp://*:5559'
