[local]
ip = [ "10.10.0.1", "185.10.83.2", "185.10.80.1" ] # список своих IP для пропуска

  # список интерфейсов
  [local.interfaces]
  internal = "enp0s3"
  external = "enp0s8"

[staticarp]
filename = "/etc/ether"

# сервер авторизации (цель для DNAT)
[auth]
ip = "185.10.83.6"

# список ipset листов
[ipset]
whitelist = "whitelist"
authlist = "authmaclist"
keepttl = "keepttl"

# список цепочек iptables
[iptables.chains]
white = "WHITE"
auth = "AUTHMARK"
ttl = "CHANGETTL"
drop = "DROPMARKED"

# настройки протоколов rpc
[rpc.zeromq]
enabled = false

  [rpc.zeromq.ports]
  push_pull = "tcp://*:5558"
  req_resp = "tcp://*:5559"
